config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show"

  get "up" => "health#show", as: :rails_health_check

  resources :teams, except: %i[show]
  resources :users

  resources :teams, module: :teams do
    get "", to: "pages#show", as: "home"

    resources :members, only: %i[index show]
    resources :memories, only: %i[index show]

    resources :locations, only: %i[show]
    resources :pictures, only: %i[show]
    resources :thoughts, only: %i[show]
    resources :weblinks, only: %i[show]

    get "/pictures_only/:id", to: "pictures_only#show", as: "picture_only"
  end

  scope ActiveStorage.routes_prefix do
    # NOTE: allow to auth user, to prevent anyone with the link from opening images
    #
    get "/blobs/redirect/:signed_id/*filename" => "authorize_blobs#show"
  end

  namespace :current_team, module: :current_teams do
    get "", to: "pages#show", as: "home"

    resources :locations
    resources :members
    resources :memories
    resources :pictures
    resources :thoughts
    resources :weblinks

    get "/content_visibility/:id/edit", to: "content_visibility#edit", as: "edit_content_visibility"
    patch "/content_visibility/:id", to: "content_visibility#update", as: "content_visibility"

    get "new_search", to: "searches#new", as: "new_search"
    post "search", to: "searches#create", as: "search"
  end

  resources :switch_current_teams, only: %i[index show create destroy]

  # Login Controller
  resources :logins, only: %i[index destroy], as: :login_records
  # Session Controller
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  namespace :admin, module: "admins", constraints: ->(request) { AdminConstraint.matches?(request) } do
    get "", to: "pages#show", as: "home"
    resources :locations
    resources :members
    resources :memories # TODO: add controllers and views
    resources :pictures
    resources :teams
    resources :users
    resources :thoughts
    resources :weblinks
    get "record_history", to: "record_history#index", as: :record_history

    # NOTE: we setup MissionControl to inherit from our AdminController to only give admins access
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end

  # catch all unknown routes to NOT throw a FATAL ActionController::RoutingError
  match "*path", to: "application#error_404", via: :all,
    constraints: ->(request) { !request.path_parameters[:path].start_with?("rails/") }
end

app/models/weblink.rb
# type: Content
#
class Weblink < ApplicationRecordForContentAndPosts
  YID_CODE = "link".freeze

  belongs_to :team, inverse_of: :weblinks

  has_many :memories, class_name: "Memory", inverse_of: :weblink,
    dependent: :nullify

  multisearchable(
    against: %i[name],
    additional_attributes: ->(weblink) { { team_id: weblink.team_id } }
  )

  attr_readonly :team_id

  normalizes :name, with: ->(name) { name.strip }
  normalizes :url, with: ->(url) { ActionDispatch::Http::URL.full_url_for(host: url.strip, protocol: "https") }

  validates :name, presence: true
  validates :team_id, uniqueness: { scope: :url }
  validates :url, presence: true, uniqueness: { scope: :team_id }
  validates :visibility, presence: true, inclusion: { in: VISIBILITY_STATES }
end

app/controllers/admins/weblinks_controller.rb
module Admins
  class WeblinksController < AdminController
    def index
      @weblinks = Weblink.all
    end

    def show
      @weblink = Weblink.urlsafe_find!(params[:id])
    end

    def new
      @weblink = Weblink.new(team: current_team)
    end

    def edit
      @weblink = Weblink.urlsafe_find!(params[:id])
    end

    # TODO: set preview_snippet by calling the URL once to also validate it
    def create
      @weblink = Weblink.new(weblink_params)

      Weblink.create_with_history(record: @weblink, history_params: { team: nil, user: current_user, done_by_admin: true })

      if @weblink.persisted?
        redirect_to admin_weblink_url(@weblink), notice: "Weblink was successfully created."
      else
        render :new, status: :unprocessable_content
      end
    end

    def update
      @weblink = Weblink.urlsafe_find!(params[:id])
      @weblink.assign_attributes(weblink_params)

      Weblink.update_with_history(record: @weblink, history_params: { team: nil, user: current_user, done_by_admin: true })

      if @weblink.changed? # == weblink still dirty, not saved
        render :edit, status: :unprocessable_content
      else
        redirect_to admin_weblink_url(@weblink), notice: "Weblink was successfully updated."
      end
    end

    def destroy
      @weblink = Weblink.urlsafe_find!(params[:id])

      Weblink.destroy_with_history(record: @weblink, history_params: { team: nil, user: current_user, done_by_admin: true })

      redirect_to admin_weblinks_url, notice: "Weblink was successfully destroyed."
    end

    private

    def weblink_params
      params.expect(weblink: %i[url name date description team_id])
    end
  end
end

app/controllers/current_teams/weblinks_controller.rb
module CurrentTeams
  class WeblinksController < AppCurrentTeamController
    skip_before_action :authenticate, only: %i[index show] # allow everyone to see the weblinks

    def index
      authorize! current_user, to: :index?, with: WeblinkPolicy

      # weblinks = authorized_scope(Weblink.all, type: :relation, as: :current_team_scope)
      weblinks = Weblink.all

      @weblinks = weblinks
    end

    def show
      @weblink = Weblink.urlsafe_find!(params[:id])
      authorize! @weblink
    end

    def new
      @weblink = Weblink.new(team: current_team)
      authorize! @weblink
    end

    def edit
      @weblink = Weblink.urlsafe_find!(params[:id])
      authorize! @weblink
    end

    # TODO: set preview_snippet by calling the URL once to also validate it
    def create
      @weblink = Weblink.new(
        url: weblink_params[:url],
        name: weblink_params[:name],
        description: weblink_params[:description],
        team: current_team
      )

      authorize! @weblink

      Weblink.create_with_history(record: @weblink, history_params: { team: current_team, user: current_user })

      if @weblink.persisted?
        redirect_to current_team_weblink_url(@weblink), notice: "Weblink was successfully created."
      else
        render :new, status: :unprocessable_content
      end
    end

    def update
      @weblink = Weblink.urlsafe_find!(params[:id])
      authorize! @weblink
      @weblink.assign_attributes(weblink_params)

      Weblink.update_with_history(record: @weblink, history_params: { team: current_team, user: current_user })

      if @weblink.changed? # == weblink still dirty, not saved
        render :edit, status: :unprocessable_content
      else
        redirect_to current_team_weblink_url(@weblink), notice: "Weblink was successfully updated."
      end
    end

    def destroy
      @weblink = Weblink.urlsafe_find!(params[:id])
      authorize! @weblink

      Weblink.destroy_with_history(record: @weblink, history_params: { team: current_team, user: current_user })

      redirect_to current_team_weblinks_url, notice: "Weblink was successfully destroyed."
    end

    private

    def weblink_params
      params.expect(weblink: %i[url name date description])
    end
  end
end

app/controllers/teams/weblinks_controller.rb
module Teams
  class WeblinksController < AppTeamsController
    def show
      @weblink = record(Weblink, params[:id])

      render "teams/weblinks/show"
    end
  end
end

app/views/admins/weblinks/_action_buttons.html.slim
= link_to "New weblink", new_admin_weblink_path, role: "button"

app/views/admins/weblinks/_form.html.slim
article
  = form_with(model: [:admin, weblink]) do |form|
    = render partial: "shared_partials/form_validation_errors", locals: { record: weblink }
    fieldset
      h3
        legend
          = form_legend
      - if weblink.persisted?
        label
          strong Team
          = weblink.team.name
          i
            = weblink.team.id
      - else
        div
          = form.label :team_id
          =
          -             form.select :team_id, Team.pluck(:name, :id), selected: form.object.team_id, include_blank: true, required: true
      div
        = form.label :name
        = form.text_field :name
      div
        = form.label :date
        = form.date_field :date, value: Date.current
      div
        = form.label :url
        = form.text_field :url
      div
        = form.label :description
        = form.text_area :description
      div
        = form.submit

app/views/admins/weblinks/_weblink.html.slim
article id= dom_id(weblink)

  p
    strong Name:
    = weblink.name
  p
    strong Url:
    = render ExternalLinkComponent.new(url: weblink.url, text: weblink.url)
  p
    strong Description:
    = weblink.description
  hr
  = render AdminShowTeamComponent.new(team: weblink.team)
  = render AdminShowMetaInformationComponent.new(record: weblink)
  = render AdminActionsComponent.new(record: weblink, name: "weblink")

app/views/admins/weblinks/edit.html.slim
= render partial: "form", locals: { weblink: @weblink, form_legend: "Edit weblink" }
= link_to "Show this weblink", admin_weblink_path(@weblink), role: "button"
= button_to "Destroy this weblink", admin_weblink_path(@weblink), method: :delete, class: "secondary"

app/views/admins/weblinks/index.html.slim
#weblinks
  = render @weblinks

app/views/admins/weblinks/new.html.slim
= render partial: "form", locals: { weblink: @weblink, form_legend: "Create weblink" }

app/views/admins/weblinks/show.html.slim
= render @weblink